receivers:
    prometheus:
        config:
            scrape_configs:
                - job_name: otel-collector
                  scrape_interval: 5s
                  static_configs:
                      - targets: ["localhost:8888"]

    otlp:
        protocols:
            grpc:
            http:

processors:
    batch:

    filter/ottl:
        error_mode: ignore
        traces:
            span:
                - 'IsMatch(attributes["log.info"], ".*secret.*")'

    memory_limiter:
        check_interval: 5s
        limit_mib: 4000
        spike_limit_mib: 500

exporters:
    logging:
        loglevel: debug

    prometheus:
        endpoint: "0.0.0.0:8889"

    prometheusremotewrite:
        endpoint: "http://prometheus:9090/api/v1/write"
        tls:
            insecure: true
        resource_to_telemetry_conversion:
            enabled: true # Convert resource attributes to metric labels

    otlp/jaeger:
        endpoint: "jaeger-all-in-one:4317"
        tls:
            insecure: true

extensions:
    health_check:
    zpages:
        endpoint: :55679

service:
    extensions: [zpages, health_check]
    pipelines:
        metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [prometheus]
        traces:
            receivers: [otlp]
            processors: [batch, filter/ottl, memory_limiter]
            exporters: [otlp/jaeger]
