global:
  scrape_interval: 10s

scrape_configs:
  - job_name: otel-collector
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8888', 'otel-collector:8889']

  - job_name: node-exporter
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:9100']

  - job_name: prometheus-exporter
    static_configs:
      - targets: ['host.docker.internal:9464']
