{
 "title": "Nodejs Metrics",
 "description": "Nodejs runtime metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "10s,30s,1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "group",
    "label": "Group",
    "query": "label_values(nodejs_active_handles, group)"
   },
   {
    "name": "stack",
    "label": "Stack",
    "query": "label_values(nodejs_active_handles{group=\"$group\"},stack)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(nodejs_active_handles,service)"
   },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(nodejs_active_handles{stack=\"$stack\",service=\"$service\"},host)"
   }
  ]
 },
 "panels": [
  {
   "title": "$service Nodejs Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nodejs_version_info{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "request_counter_middleware_total{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}} {{clientId}} {{method}} {{statusCode}} {{statusMessage}} {{url}}"
    }
   ]
  },
  {
   "title": "Request Excecute Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "request_histogram_middleware_sum",
     "legendFormat": "{{service}} {{clientId}} {{method}} {{statusCode}} {{statusMessage}} {{url}}"
    }
   ]
  },
  {
   "title": "$service Process Heap",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_heap_bytes{stack=~\"$stack\",service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service Process start time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(process_start_time_seconds{service=~\"$service\", stack=~\"$stack\"})*1000",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "$service Max file descriptors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 2 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_max_fds{stack=~\"$stack\",service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "$service Metrics scrape duration",
   "type": "stat",
   "gridPos": { "h": 14, "w": 4, "x": 0, "y": 4 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scrape_duration_seconds{stack=~\"$stack\",service=~\"$service\", host=~\"$host\"}"
    }
   ]
  },
  {
   "title": "$service Open file descriptors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_open_fds{stack=~\"$stack\",service=~\"$service\"}"
    }
   ]
  },
  {
   "title": "% CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 4, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total{service=~\"$service\", stack=~\"$stack\"}[$interval])",
     "legendFormat": "{{service}} User"
    },
    {
     "expr": "rate(process_cpu_system_seconds_total{service=~\"$service\", stack=~\"$stack\"}[$interval])",
     "legendFormat": "{{service}} System"
    },
    {
     "expr": "rate(process_cpu_seconds_total{service=\"$service\", stack=~\"$stack\"}[$interval])",
     "legendFormat": "{{service}} Total"
    }
   ]
  },
  {
   "title": "Event loop lag",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}} Event Loop Lag"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "External Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "nodejs_external_memory_bytes{service=~\"$service\", stack=~\"$stack\"}",
       "legendFormat": "{{service}} External Memory"
      }
     ]
    },
    {
     "title": "Heap size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "nodejs_heap_size_total_bytes{service=~\"$service\", stack=~\"$stack\"}",
       "legendFormat": "{{service}} Total"
      },
      {
       "expr": "nodejs_heap_size_used_bytes{service=~\"$service\", stack=~\"$stack\"}",
       "legendFormat": "{{service}} Used"
      }
     ]
    },
    {
     "title": "Process Memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{service=~\"$service\", stack=~\"$stack\"}",
       "legendFormat": "{{service}} Resident"
      },
      {
       "expr": "process_virtual_memory_bytes{service=~\"$service\", stack=~\"$stack\"}",
       "legendFormat": "{{service}} Virtual"
      }
     ]
    }
   ]
  },
  {
   "title": "Heap Space Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}} {{space}}"
    }
   ]
  },
  {
   "title": "Available",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}}-{{space}}"
    }
   ]
  },
  {
   "title": "Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}} {{space}}"
    }
   ]
  },
  {
   "title": "Hyper Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hyper success requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hyper_provider_success_request_counter_total{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}} {{method}} {{url}} {{params}} {{body}} {{executeTime}}ms"
    }
   ]
  },
  {
   "title": "Hyper fail requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hyper_provider_fail_request_counter_total{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{service}} {{errorCode}} {{errorMessage}} {{method}} {{url}} {{params}} {{body}}"
    }
   ]
  },
  {
   "title": "Hyper request execute time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "hyper_provider_request_histogram_sum{service=~\"$service\", stack=~\"$stack\"}",
     "legendFormat": "{{method}} {{url}} {{executeTime}}ms"
    }
   ]
  }
 ]
}